## Lesson 2 

### Тема “Вычисления с помощью Numpy”

Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать,
что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по
каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в
нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]]
              )

In [3]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [4]:
mean_a = a.mean(axis=0)

In [5]:
print(mean_a)

[2.  8.4]


Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих
признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [6]:
a_centered = a - mean_a  # от матрицы отнимаем средние значение

In [7]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться
величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [8]:
colum1 = a_centered[0:, :1].copy()  # создаем срез 1-го столбца

In [9]:
print(colum1)

[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]


In [10]:
colum2 = a_centered[0:, 1:].copy()  # создаем срез 2-го столбца

In [11]:
print(colum2)

[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]


In [12]:
a_centered_sp = colum1 * colum2  # столбцы переумножаем между собой

In [13]:
print(a_centered_sp)

[[ 2.4]
 [-0. ]
 [ 2.6]
 [ 1.6]
 [ 1.4]]


In [14]:
# a_centered_sp2 = a_centered.dot(colum2)

In [15]:
# a_centered_sp2

Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на
N, поэтому полученная нами величина является несмещенной оценкой ковариации.

### Тема “Работа с данными в Pandas”

Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со
столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и
['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно
содержатся данные:
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и
поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [16]:
import pandas as pd

In [17]:
authors_dict = {
    'author_id':[1, 2, 3],
    'author_name':['Тургенев', 'Чехов', 'Островский'] 
}

In [18]:
authors = pd.DataFrame(authors_dict)

In [19]:
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [20]:
book_dict = {
    "author_id":[1, 1, 1, 2, 2, 3, 3],
    "book_title":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 
                  'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

In [21]:
book = pd.DataFrame(book_dict)

In [22]:
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [23]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')

In [24]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими
книгами.

In [25]:
top5 = pd.merge(authors, book, on='author_id', how='inner')

In [26]:
top5.nlargest(5, "price")

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat
должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя
цена на книги этого автора.

In [30]:
authors_stat = pd.DataFrame(authors_price['author_name'])
# authors_stat

In [31]:
authors_stat[['min', 'max', 'maen']]=1
authors_stat

author_name  min  max  maen
0    Тургенев    1    1     1
1    Тургенев    1    1     1
2    Тургенев    1    1     1
3       Чехов    1    1     1
4       Чехов    1    1     1
5  Островский    1    1     1
6  Островский    1    1     1

Задание 5**
1Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться
данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные
из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого
автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого
функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами
должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при
необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием
"book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь,
что датафреймы book_info и book_info2 идентичны.